version: '3.8'

services:
 observer-0:
   image: elrondnetwork/elrond-node-obs:e1.1.0.1
   ports:
     - "8080:8080"
     - "10000:37373"
   environment:
     - SHARD=0
     - DISPLAY_NAME="MyObservingSquad-0"
     - OBSERVER_DIR=~/MyObservingSquad/node-0
     - IP=10.0.0.6
   volumes:
     - ~/MyObservingSquad/node-0/db:/go/elrond-go/cmd/node/db
     - ~/MyObservingSquad/node-0/logs:/go/elrond-go/cmd/node/logs
     - ~/MyObservingSquad/node-0/config:/config
   command: --destination-shard-as-observer=0 --validator-key-pem-file=/config/observerKey_0.pem --display-name="MyObservingSquad-0"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.6

 observer-1:
   image: elrondnetwork/elrond-node-obs:e1.1.0.1
   ports:
     - "8081:8080"
     - "10001:37373"
   environment:
     - SHARD=1
     - DISPLAY_NAME="MyObservingSquad-1"
     - OBSERVER_DIR=~/MyObservingSquad/node-1
     - IP=10.0.0.5     
   volumes:
     - ~/MyObservingSquad/node-1/db:/go/elrond-go/cmd/node/db
     - ~/MyObservingSquad/node-1/logs:/go/elrond-go/cmd/node/logs
     - ~/MyObservingSquad/node-1/config:/config
   command: --destination-shard-as-observer=1 --validator-key-pem-file=/config/observerKey_1.pem --display-name="MyObservingSquad-1"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.5
 observer-2:
   image: elrondnetwork/elrond-node-obs:e1.1.0.1
   ports:
    - "8082:8080" 
    - "10002:37373"
   environment:
     - SHARD=2
     - DISPLAY_NAME="MyObservingSquad-2"
     - OBSERVER_DIR=~/MyObservingSquad/node-2
     - IP=10.0.0.4
   volumes:
     - ~/MyObservingSquad/node-2/db:/go/elrond-go/cmd/node/db
     - ~/MyObservingSquad/node-2/logs:/go/elrond-go/cmd/node/logs
     - ~/MyObservingSquad/node-2/config:/config
   command: --destination-shard-as-observer=2 --validator-key-pem-file=/config/observerKey_2.pem --display-name="MyObservingSquad-2"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.4

 observer-meta:
   image: elrondnetwork/elrond-node-obs:e1.1.0.1
   ports:
     - "8083:8080"
     - "10003:37373"
   environment:
     - SHARD=metachain
     - DISPLAY_NAME="MyObservingSquad-metachain"
     - OBSERVER_DIR=~/MyObservingSquad/node-metachain
     - IP=10.0.0.3
   volumes:
     - ~/MyObservingSquad/node-metachain/db:/go/elrond-go/cmd/node/db
     - ~/MyObservingSquad/node-metachain/logs:/go/elrond-go/cmd/node/logs
     - ~/MyObservingSquad/node-metachain/config:/config
   command: --destination-shard-as-observer=metachain --validator-key-pem-file=/config/observerKey_metachain.pem --display-name="MyObservingSquad-metachain"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.3

 proxy:
   image: elrondnetwork/elrond-proxy:v1.1.1
   ports:
     - "8079:8079"
   environment:
     - IP=10.0.0.2
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.2

networks:
  elrond-squad:
    ipam:
      config:
        - subnet: 10.0.0.0/24