env:
  REGISTRY_HOSTNAME: multiversx

name: Build Docker images

on:
  push:
    branches: [ master, development, feat/*, rc/* ]
  pull_request:
    branches: [ master, development, feat/*, rc/* ]
jobs:
  build-docker-images:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Import environment variables from a file
        shell: bash
        run: |
          ENV_FILE="${GITHUB_WORKSPACE}/mainnet/.env"
          while read -r line; do
            if [[ "$line" != OBSERVER_IMAGE* ]] && [[ "$line" != PROXY_IMAGE* ]] ; then
              continue
            fi
            echo "$line" >> $GITHUB_ENV
          done < ${ENV_FILE}
      - name: Build node image
        run: |
          cd ${GITHUB_WORKSPACE}/mainnet/ && docker image build . -t "${REGISTRY_HOSTNAME}/${OBSERVER_IMAGE}" -f ./chain-observer
      - name: Build proxy image
        run: |
          cd ${GITHUB_WORKSPACE}/mainnet/ && docker image build . -t "${REGISTRY_HOSTNAME}/${PROXY_IMAGE}" -f ./chain-proxy
